version: "3.8"
services:
  hapi:
    image: hapiproject/hapi:latest
    container_name: hapifhir
    ports:
      - "8080:8080"
    environment:
      - HAPI_FHIR_CONTEXT_PATH=/fhir
      - HAPI_FHIR_VERSION=R4